# Generated by Django 2.2.24 on 2021-07-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210729_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(null=True, related_name='_profile_follow_+', to='social.Profile'),
        ),
    ]
