# Generated by Django 2.2.24 on 2021-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to=''),
        ),
    ]
